[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/editor.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
termion = { workspace = true }
utils = { path = "../utils" }
